### ISSUE TITLE
Error: reporter "wdio-spec-reporter" is not installed

### ISSUE THREAD

**Issue by thyngster** [sahava/gtm-datalayer-test#5]
Current master throws an error when installing from scratch:

/home/work/gtm-datalayer-test/node_modules/webdriverio/build/lib/launcher.js:162
                        throw _iteratorError;
                        ^

Error: reporter "wdio-spec-reporter" is not installed. Error: Error: Cannot find module 'wdio-spec-reporter'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Launcher.initReporters (/home/work/gtm-datalayer-test/node_modules/webdriverio/build/lib/launcher.js:137:41)
    at new Launcher (/home/work/gtm-datalayer-test/node_modules/webdriverio/build/lib/launcher.js:73:31)
    at Object.<anonymous> (/home/work/gtm-datalayer-test/node_modules/webdriverio/build/lib/cli.js:426:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at Launcher.initReporters (/home/work/gtm-datalayer-test/node_modules/webdriverio/build/lib/launcher.js:139:35)
    at new Launcher (/home/work/gtm-datalayer-test/node_modules/webdriverio/build/lib/launcher.js:73:31)
    at Object.<anonymous> (/home/work/gtm-datalayer-test/node_modules/webdriverio/build/lib/cli.js:426:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by thyngster** [comment]
Following commands fixes it:

`cd node_modules/wdio-spec-reporter/`
`npm install`
`npm install -g grunt-cli`
`grunt build`

**Comment by sahava** [comment]
Looks like the issue is when running npm install for gtm-datalayer-test as a root / sudo user. It needs to be run as a local user.

Potential fixes:
- Throw an error if root / sudo, and require local user access
- Add `--unsafe-perm` to npm install in wdio-spec-reporter to disregard sudo user (security risk?)
